version: '3.8'

services:
  mysql:
    image: mysql:8.0.12
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123  # Change this to a secure password
      MYSQL_DATABASE: youtube_data
      MYSQL_USER: user
      MYSQL_PASSWORD: Shriyantra@01 # Change this to a secure password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
